### ISSUE TITLE
Functions in <leader>t terminal have the same error?

### ISSUE THREAD

**Issue by datamonsterr** [kabinspace/AstroVim#135]
![Screenshot_20220309_171648](https://user-images.githubusercontent.com/94211882/157421787-8d31dc07-dfe4-41a5-9fa1-81bd3948ce09.png)
This is the error I meet everytime I try to use lazygit htop or some thing in <leader>t options. How can I fix that?
I use Manjaro Kde, Nvim 0.6.1 with Astrovim.

**Comment by mehalter** [comment]
@datamonsterr this is due to the lazy loading of ToggleTerm. First you have to open a terminal with the `ctrl-\` binding before the terminal plugin is loaded and then these functions will be available. This can be resolved by removing this line in your installation: https://github.com/kabinspace/AstroVim/blob/cb7c10c8b95d139c3c1aab14255911dbbaa05f6a/lua/core/plugins.lua#L289

Or recently we have added the ability to do this in your `settings.lua` file by adding this to the config table:

```lua
local config = {
  -- ...rest of config
  
  polish_plugins = function(plugins)
    local result = {}
    for _, plugin in pairs(plugins) do
      if plugin[1] == "akinsho/nvim-toggleterm.lua" then
        plugin["cmd"] = nil
      end
      table.insert(result, plugin)
    end
    return result
  end,
}
```

**Comment by datamonsterr** [comment]
Thanks for your solution, it works perfectly!

**Comment by mehalter** [comment]
@datamonsterr just a heads up I have a PR open that will resolve this issue and allow for the lazy loading to be enabled and these toglges work #241
