### ISSUE TITLE
Question: Comparison with other Vim Distros

### ISSUE THREAD

**Issue by rieger-jared** [kabinspace/AstroVim#176]
Hi,

I was wondering if you knew about other projects like `lunarvim`, `spacevim` and so on. What does this distro provide that the others do not?

**Comment by kabinspace** [comment]
"Simplicity" is what AstroVim provides compared to other distros. AstroVim is comparatively simpler than the distros that you mentioned above. Some distros are simpler than AstroVim as well. Now people got many options to choose from according to their liking. Also, you can see that we have mentioned AstroVim as an "aesthetic" because we provide a clean and beautiful user interface which people seem to be loving most about the AstroVim :)
