### ISSUE TITLE
The TermExec command is not working.

### ISSUE THREAD

**Issue by Rid1-fz-06** [kabinspace/AstroVim#183]
For some kind of reason the TermExec command of toggleterm is not working until I use <leader>tf or any similar command to open toggleterm manually. I need to use this command to compile my code. Will you please fix this?

**Comment by mehalter** [comment]
@Rid1-fz-06 this is due to the lazy loading of ToggleTerm. The terminal must first be open and closed with the `ctrl-\` binding to load the plugin. Once this happens then it will be available. If you would like to disable this lazy loading please refer to the Advanced Configuration page in the Wiki. It includes an example on how to disable the lazy loading of a default plugin: https://github.com/kabinspace/AstroVim/wiki/Advanced-Configuration#override-function

**Comment by mehalter** [comment]
@Rid1-fz-06 just a heads up I have a PR open that will resolve this issue and allow for the lazy loading to be enabled and these toglges work #241
