### ISSUE TITLE
[Question] Overriding keybinding, what am I doing wrong.

### ISSUE THREAD

**Issue by rjshrjndrn** [kabinspace/AstroVim#196]
Hi,
First of all thank you for this amazing distro. Loved the aesthetics. But I wanted to override `cmp` keymap from `c-j` to `tab` for selecting the suggestions. But something is not working. Can you please tell me what am I missing? 
> `c-x` is just a debug keybinding.

![image](https://user-images.githubusercontent.com/2563385/159910056-bf1e7d85-fc78-4760-ac03-7d238536df11.png)

**Comment by mehalter** [comment]
Great question @rjshrjndrn this is not working because `cmp` is not defined in your `init.lua`. There are a couple ways to access this (these are both described in the [Advanced Configuration](https://github.com/kabinspace/AstroVim/wiki/Advanced-Configuration#supported-initlua-override-formats) section of the wiki)

1. You can use a function for the `cmp` overriding in `init.lua`. Functions here are lazy loaded when they are needed so you will be able to do `require("cmp")`. This would have your `init.lua` file look like this:

```lua
return {
  plugins = {
    cmp = function(table)
      -- table parameter is the default table
      -- the function is lazy loaded so cmp is able to be required
      local cmp = require "cmp"
      -- modify the mapping part of the table
      table.mapping["<C-x>"] = cmp.mapping.select_next_item()

      -- return the new table to be used
      return table
    end,
  },
}
```

2. You can use a separate file outside of your `init.lua`. In the `init.lua` the `cmp` override is located at `plugins.cmp`, this would be reflected in your `user/` folder as `user/plugins/cmp.lua` and these files are lazy loaded as well so you can do something closer to your override table you have now where `user/plugins/cmp.lua` would look like this:

```lua
local cmp = require "cmp"

return {
  mapping = {
    ["<C-x>"] = cmp.mapping.select_next_item(),
  },
}
```

**Comment by rjshrjndrn** [comment]
Sorry for the late response @mehalter. Thank you for the detailed answer.
