### ISSUE TITLE
[Question] pyright analyses 180 files on every change

### ISSUE THREAD

**Issue by nschloe** [kabinspace/AstroVim#256]
(Perhaps this isn't the right repo to ask the question, but maybe you can help me out anyway or forward me to the right place.)

I just tried out AstroVim for the first time and I'm delighted! I noticed though that pyright analyzes 180+ files on the slightest change, leading to my laptop's fans never spinning down. Any idea why this might be, or how to prevent it?

**Comment by mehalter** [comment]
I haven't uhttpssed pyright for any projects that large so I'm not sure the best way to handle it. I would take a look at https://github.com/microsoft/pyright/issues and see if anyone has had a similar question to pyright in particular.

If you come up with an answer it would be great if you could comment back with any tidbits for future users who might run into a similar problem!

**Comment by nschloe** [comment]
It's probably not an issue in pyright itself, but some part of the nvim toolchain. Could you enlighten me on how pyright is called, how the files to check are selected etc.?

**Comment by mehalter** [comment]
Neovim LSP has a mechanism for identifying the root directory of a project. Here is the default:

https://github.com/neovim/nvim-lspconfig/blob/f183d35725264d6184146eebcef1ba8338ddbc83/lua/lspconfig/server_configurations/pyright.lua#L10

It looks like it traverses the directory structure to find one of the listed files and then sets that as the project root. Once it identifies the project root it sets up pyright to analyze files inside that directory.

I did look at some of the pyright issues as well and it looks like it should be doing lazy analysis so that makes me think it should keep it from having to immediately analyze all of the files in that directory until it gets to needing that information

**Comment by mehalter** [comment]
Also single file mode is on by default so if it doesn't find one of those root directory files then it should just index the file that you have open.

**Comment by nschloe** [comment]
Thanks for the comments!

> It looks like it traverses the directory structure to find one of the listed files and then sets that as the project root. Once it identifies the project root it sets up pyright to analyze files inside that directory.

Yeah, I notice too pyright picks up on the changes I'm doing in my project's `pyproject.toml`, e.g.,
```toml
[tool.pyright]
include = ["src"]
```
so that seems okay. I also have `openFilesOnly` diagnostic mode

![sc2](https://user-images.githubusercontent.com/181628/161918356-9f3c656d-e170-4fc7-acba-61826ca7b77e.png)

Still, on every single file change, I'm getting

![sc1](https://user-images.githubusercontent.com/181628/161918467-bd1d294d-d45e-44c9-bca5-4c32f838a5d6.png)

I'll try to get help from the lsp folks.
