### ISSUE TITLE
Changing background to transparent

### ISSUE THREAD

**Issue by sudoFerraz** [kabinspace/AstroVim#33]
Hello, not really an issue;

Unfortunately my first time using a Lua setup, and I'm struggling to understand how I can setup the onedark_transparent flag on this config structure.

https://github.com/ful1e5/onedark.nvim

Any hints?

**Comment by kabinspace** [comment]
Since AstroVim has a built-in one dark theme already, it will cause conflict with the name of other one dark plugins. I would suggest you use either theme with a different name or make a custom transparency mode inside AstroVim like [this](https://github.com/kabinspace/AstroVim/issues/8#issuecomment-1030605974)
