### ISSUE TITLE
Errors running AstroUpdate

### ISSUE THREAD

**Issue by ericlake** [kabinspace/AstroVim#50]
When running a `:AstroUpdate` I am seeing the following error

```
update failed! table: 0x0105758518
```
![image](https://user-images.githubusercontent.com/216564/153679153-829695ac-d1a7-425b-87af-dcf487f2b344.png)

I have some setting changes in my `~/.config/nvim` dir but I am not sure why they would prevent an update. Is there something special that needs to be done when making changes to the configuration so that it does not conflict with updates?

**Comment by ericlake** [comment]
I had to stash the local changes first and then run the update again. It seems that there was a conflict in the `lua/core/plugins.lua` file between my local changes and upstream.

**Comment by kabinspace** [comment]
@ericlake You can't get any updates if you bring any changes to any other place except for `lua/user` directory as it might bring conflicts. This was done so that your custom files and settings won't go away when updating AstroVIm. Sometimes updating might fail even though you didn't make any changes in other places but it should work after a couple of tries.
