### ISSUE TITLE
How to auto reload the config when something in `user/settings.lua` changes?

### ISSUE THREAD

**Issue by bjufre** [kabinspace/AstroVim#94]
I tried adding this in:

```lua
vim.cmd [[
  augroup packer_conf
    autocmd!
    autocmd bufwritepost plugins.lua source <afile> | PackerSync
  augroup end
]]

vim.cmd [[
  command! ReloadConfig lua require("plenary.reload").reload_module("init") -- Or "lua.user.settings" but nothing
]]
```

**Comment by mehalter** [comment]
I'm not sure of a good way to do this. I have tried going down a few rabbit holes and nothing I have tried seems to successfully release the full lua config. Sadly, this will probably be unsupported, but if you find a way to do this please let us know!

**Comment by snewell92** [comment]
I also have sought after and tried this, may my findings help the next person who finds this. I decided not to open a new issue, as this one is from this year, and I'm pretty sure there isn't an immediately obvious solution for AstroVim to adopt (whenever/if we do find out, it would be awesome to have a `:AstroVim.ReloadUserConfig` or `ReloadAll` something similar 🙏🏼 .

## The Goal 🥇 

I want to be able to tinker and experiment with my config, reload, test it out, tinker, reload... etc until I'm happy with my new mapping, its functionality, and decide to not only stop writing to whatever `init.lua` (most often my own user mappings defined in `user/init.lua`) but also commit those and push them to my own `dotfiles` repo which syncs across all my machines and the internets, sharing my wild crazy neovim experiments with all.

## The Problem 💢 

You can `:so %s` anytime when in normal `vim` and messing with `.vimrc` file, and even while messing about in `lua` you can `:so %s` and neovim will load that lua file, so if you have a very simple lua file somewhere that you want to load and test functions or something, that will work great, but if you are trying to edit a file like `lua/user/init.lua` for AstroVim's user config, reloading that file won't reapply the settings.

The root of the problem tied to how lua's module system and `require` calls work and are implemented. See details [in the manual](https://www.lua.org/manual/5.1/manual.html#5.3) for how require, modules, and the internal global store works with `package.loaded[name]`.

## The Avenues 🦶🏼 

AstroVim comes with `plenary` which has a [reload](https://github.com/nvim-lua/plenary.nvim/blob/3e0e3af5208d95a2d37d04a2fa246d8aace97383/lua/plenary/reload.lua) function.

You can iterate over all packages loaded by looking at the table `package.loaded`'s keys. You can filter the generated key list to find the exact module name/id you are interested in. The problem is, of course, that you likely will need to know and iterate over _all_ modules in the module tree that end up requiring your user config. I _thought_ astrovim would just require your user config from the main `init.lua`, but that still didn't seem to work.

<details>
<summary>Some code that does pieces of all that</summary>

```lua
local Path = require('plenary.path')
local scan_dir = require('plenary.scandir').scan_dir

-- !! This did not do what I expected, I really wanted to be able to 
-- reload just the user config in the astrovim setup, but it's just too
-- hard I guess.

-- Check if path exists
local function path_exists(path)
    return Path:new(path):exists()
end

-- Escape lua string
local function escape_str(str)
    local patterns_to_escape = {
        '%^',
        '%$',
        '%(',
        '%)',
        '%%',
        '%.',
        '%[',
        '%]',
        '%*',
        '%+',
        '%-',
        '%?'
    }

    return string.gsub(
        str,
        string.format("([%s])", table.concat(patterns_to_escape)),
        '%%%1'
    )
end

local function get_lua_modules_in_path(luapath)
    -- local luapath = string.format("%s/lua", runtimepath)

    if not path_exists(luapath) then
        return {}
    end

    -- Search lua directory of runtimepath for modules
    local modules = scan_dir(luapath, { search_pattern = '%.lua$', hidden = true })

    for i, module in ipairs(modules) do
        -- Remove runtimepath and file extension from module path
        module = string.match(
            module,
            string.format(
                '%s/(.*)%%.lua',
                escape_str(luapath)
            )
        )

        -- Changes slash in path to dot to follow lua module format
        module = string.gsub(module, "/", ".")

        -- If module ends with '.init', remove it.
        module = string.gsub(module, "%.init$", "")
        -- Override previous value with new value
        modules[i] = module
    end

    return modules
end

local test_path = "/Users/snew/.config/nvim/"
-- local modules_in_test_path = get_lua_modules_in_path(test_path, 'user')
-- print(vim.inspect(get_lua_modules_in_path(test_path)))

local keyset={}
local n=0

for k,_ in pairs(package.loaded) do
  if string.match(k, "config") == "config" then
    n=n+1
    keyset[n]=k
  elseif string.match(k, "mapping") == "mapping" then
    n=n+1
    keyset[n]=k
  end
end

for _,k in pairs(keyset) do
  package.loaded[k] = nil
end

vim.cmd('luafile ~/.config/nvim/init.lua')
```

</details>

This led me to try and manually iterate and `nil` out `package.loaded`, but again, doing this properly I _think_ would be equivalent to wiping out the entire `package.loaded` table ... which I've tried too (`package.loaded = {}`) but it doesn't work (even looping over all keys in `package.loaded` and `nil`ing each out, like this [example test does](https://stackoverflow.com/a/61998449/2378943), does not seem to work).

I have not yet attempted to edit the module loading function, as lua does allow you to override that, and perhaps I could bypass the cache for everything in `.config/nvim/lua` or something (might be bad? might be OK?)

## Workaround ⛑️ 

1. Quit and Restart, but use Sessions? 💾 

The good thing about neovim, even with an AstroVim, is that it is wicked fast to startup. When making a change, it's easy to do `<leader>q`, back to terminal, and redo `nvim .` or `neovide ./path/to/folder` (or.. you know, just press `<UP>` arrow and enter because the only thing you use a terminal like `iTerm` is to launch neovim, right? ;P). The drawback, is of course any setup you may have had going via which files are open, windows, sessions, etc, is all lost. But vim as `:mksession` and `:source /path/to/session.vim` which can be plugin-ified with [session-manager](https://github.com/Shatur/neovim-session-manager), which is great!

2. Simplify Simplify Simplify 👍🏼 

A couple of options here:

- Use `polish` for all re-loadable config, and just re-invoke the polish function.
- Rip out user config and just have one top level `lua` that can get called and resourced that will overwrite things, similar to the `polish` function, but a standalone file - this will work as doing `:luafile %` or `:so %` will reload the current file, and should re apply anything in there, vimscript or lua.

**Conclusion**

So that's where we're at. We've tried manually clearing `package.loaded`, we've hoped for `plenary`'s `reload.lua`, and we've tried to reload all the things.

**Comment by mehalter** [comment]
@snewell92 could you check out this announcement from today? :) https://github.com/AstroNvim/AstroNvim/discussions/862

And see what you think!

**Comment by snewell92** [comment]
@mehalter I will buy you anything you want. (price cap of £20) (but seriously gonna look at sponsor now... xD)

**Comment by snewell92** [comment]
THIS WORKS BRILLIANTLY!!! YAAAAASSSS!! `:AstroReload` and:

```lua
mappings = {
    n = {
      ["<leader><leader>rp"] = { ":AstroReload<cr>", desc = "Reloads config" },
   }
}
```

**Comment by mehalter** [comment]
@snewell92 Thanks so much for the support! Also thank you a ton for the write up, I'm going to go through it and see if I can use it to improve the current experimental implementation. 

AstroNvim's configuration is definitely tricky to reload because the user configuration is interlaced with the base configuration on load which allows us to improve performance and also allow the user to fully remove/overwrite the base configuration from the ground up before it is ever set.

Just some warning, I believe it should be pretty solid but I have noticed some weirdness with some language servers. `lspconfig` has code in it to handle reloading of configuration nicely, but some language servers in particular don't seem to handle this process well. For example, `sumneko_lua`, `htmlls`, `cssls`, and `clangd` in my testing are rock solid. But `pyright` and `sqls` seem to spin up an increasing number of clients as you reload 😞 

It is nice that `sumneko_lua` works well because it means if you are actively working on your config, the live reloading plays particularly nice with that use case. Also if you enable the automatic reloading and quitting for updates the issue of instability after the reloading becomes a non-issue since AstroNvim just immediately quits.

Please let me know if you have any issues with the Live Reloading because I am extremely worried about how buggy it could end up being 😅

**Comment by danielbisar** [comment]
Example

```
:autocmd BufWritePost nvim-tree-setup.lua luafile <afile>
```

works just fine (with vanilla nvim 0.8.0
